config/routes.rb
Blog::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users
  resources :articles do
    resources :comments
  end
  root 'articles#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(current_user)
    @user = current_user || User.new
    if @user.admin?
      can(:manage, :all)
    else
      can(:read, :all)
      can(:manage, [Article, Comment], user: @user)
      can(:manage, User, id: @user.id)
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments

  def full_name
    if name.nil?
      email
    else
      "#{name} #{surname}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :article_find, only: [:edit, :update, :destroy, :show]
  load_and_authorize_resource only: [:update, :edit, :destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

    def article_find
      @article = Article.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :find_article, only: [:create, :new, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.article = @article
    if @comment.save
      redirect_to article_path(@comment.article)
    else
      render 'form'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_article
      @article = Article.find(params[:article_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :user_find, only: [:update, :edit, :show]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    @user.update_attributes(user_params)
    if @user.errors.empty?
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:avatar, :name, :surname)
    end

    def user_find
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br
      = f.text_field :title
  %p
    = f.label :text
    %br
      = f.text_field :text
  %p
    = f.submit
%script{:src => "//cdn.ckeditor.com/4.4.5/standard/ckeditor.js"}

app/views/articles/edit.html.haml
%h1 Editing article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/index.html.haml
- @articles.each do |article|
  .row{id: "issue_#{article.id}"}
    .col-md-2
      .pull-right
        %section.grid_2.day
          %time{:datetime => article.created_at.to_s(:db), :pubdate => "pubdate"}
            %span.date-day= article.created_at.strftime("%d")
            %span.date-month
              \.#{article.created_at.strftime("%m")}
            %span.date-year= article.created_at.strftime("%Y")
    .col-md-10
      = link_to article.title, article_path(article)
      %span/
      = article.text
  %hr/

app/views/articles/new.html.haml
%h1 New Article
= render 'form'
= link_to "Back", articles_path

app/views/articles/show.html.haml
.row
  .col-md-2
    = image_tag @article.user.avatar, with: 80, height: 80, class: "img-circle"
    %br/
    = @article.user.full_name
  .col-md-10
    %h5
      = @article.title
      %small
        - if can? :manage, @article
          = link_to '', edit_article_path(@article), class: "glyphicon glyphicon-pencil"
    %hr/
    %h4
      = @article.text
%hr/
= render @article.comments
%h2
  Add comment
= render 'comments/form'
= link_to 'Back', articles_path, class: "btn-sm btn btn-default"

app/views/comments/_comment.html.haml
%blockquote{id: "comment_#{comment.id}"}
  %p
    = comment.body
    %small
      = time_ago_in_words comment.created_at
  %small
    = comment.user.full_name
    = image_tag comment.user.avatar, with: 20, height: 20
    - if can? :manage, comment
      = link_to '', [comment.article, comment], class: "glyphicon glyphicon-remove", method: :delete, data: {confirm: 'Are you sure?'}

app/views/comments/_form.html.haml
= form_for(:comment, url: article_comments_path(article_id: @article)) do |f|
  %p
    = f.label :body
    %br/
    = f.text_field :body, size: "70x20"
  %p
    = f.submit

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %p.center
      by Ignatov Vlad

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .navbar-header
    = link_to 'shaco', articles_path, class: 'navbar-brand'
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        = link_to 'new issue', new_article_path
      %li
        = link_to 'users', users_path
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = current_user.email
            %span.caret
          %ul.dropdown-menu
            %li{:role => "presentation"}
              = link_to 'Profile', user_path(current_user)
            %li{:role => "presentation"}
              = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/_shim.html.haml
:javascript
  src="http://html5shim.googlecode.com/svn/trunk/html5.js">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/users/edit.html.haml
%h1
  Profile
  %small
    = @user.email
= form_for @user do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :surname
    = f.text_field :surname
  %p
    %label
      = t('.my_avatar')
    = image_tag(@user.avatar_url, with: 100, height: 150) if @user.avatar?
    %br/
    %br/
    = f.file_field :avatar
    = f.hidden_field :avatar_cache
  = f.submit

app/views/users/index.html.haml
#usersall
  .usersearch
    .user-browser
      %table
        %tbody
          - @users.each do |user|
            %tr
              %td
                .user-info
                  .user-avatar
                    = link_to image_tag(user.avatar, width: 40, height: 40), user_path(user)
                  .user-detail
                    = user.full_name
                    %span.user-location
                    %span.user-score
                  .user-tag

app/views/users/show.html.haml
.row
  .col-md-4.head
    = @user.full_name
    %span
    = image_tag @user.avatar, with: 120, height: 120
    %br/
    %br/
    reputation
  .col-md-4.info
    = "less info"
    %span
    %table.info
      %tbody
        %tr
          %th
            bio
            %br/
          %td
            website
          %td
        %tr
          %th
          %td
            location
          %td
        %tr
          %th
          %td
            age
          %td
      %tbody
        %tr
          %th
            visits
            %br/
          %td
            member for
          %td
        %tr
          %th
          %td
            visits
          %td
      %tbody
        %tr
          %th
            stats
          %td
            profile views
          %td
      %tbody
        %tr
          %th
            private
            %br/
          %td
            email
          %td
            = @user.email
        %tr
          %th
          %td
            real name
          %td
            = @user.full_name

  .col-md-4.about
    - if can? :manage, @user
      = link_to 'edit', edit_user_path(@user)
      |
      = link_to 'delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure?'}
      |
    preferences
    %span
    about me